// src/svelte/FCStepper.svelte
<script lang="ts">
  import { createEventDispatcher } from 'svelte';
  
  export let currentStep: number = 0;
  export let steps: Array<{title: string, description?: string}> = [];
  export let showNavigation: boolean = true;
  
  const dispatch = createEventDispatcher();
  
  function next() {
    if (currentStep < steps.length - 1) {
      currentStep++;
      dispatch('currentStepChange', currentStep);
    }
  }
  
  function previous() {
    if (currentStep > 0) {
      currentStep--;
      dispatch('currentStepChange', currentStep);
    }
  }
</script>

<div class="fc-stepper">
  <div class="fc-stepper-header">
    {#each steps as step, i}
      <div class="fc-step {currentStep === i ? 'fc-step-active' : ''} {i < currentStep ? 'fc-step-completed' : ''}">
        <div class="fc-step-icon">
          {#if i < currentStep}
            <span>✓</span>
          {:else}
            <span>{i + 1}</span>
          {/if}
        </div>
        <div class="fc-step-content">
          <div class="fc-step-title">{step.title}</div>
          {#if step.description}
            <div class="fc-step-description">{step.description}</div>
          {/if}
        </div>
      </div>
    {/each}
  </div>
  <div class="fc-stepper-content">
    <slot />
  </div>
  {#if showNavigation}
    <div class="fc-stepper-footer">
      <button class="fc-btn fc-btn-secondary" on:click={previous} disabled={currentStep === 0}>
        Trước
      </button>
      <button class="fc-btn fc-btn-primary" on:click={next} disabled={currentStep === steps.length - 1}>
        Tiếp
      </button>
    </div>
  {/if}
</div>

// src/angular/fc-stepper.component.ts
import { Component, Input, Output, EventEmitter, ContentChildren, QueryList, AfterContentInit } from '@angular/core';

@Component({
  selector: 'fc-step',
  template: `
    <div [ngClass]="['fc-step', active ? 'fc-step-active' : '', completed ? 'fc-step-completed' : '']">
      <div class="fc-step-icon">
        <span *ngIf="!completed">{{ index + 1 }}</span>
        <span *ngIf="completed">✓</span>
      </div>
      <div class="fc-step-content">
        <div class="fc-step-title">{{ title }}</div>
        <div class="fc-step-description" *ngIf="description">{{ description }}</div>
      </div>
    </div>
  `
})
export class FCStepComponent {
  @Input() title: string = '';
  @Input() description: string = '';
  @Input() active: boolean = false;
  @Input() completed: boolean = false;
  @Input() index: number = 0;
}

@Component({
  selector: 'fc-stepper',
  template: `
    <div class="fc-stepper">
      <div class="fc-stepper-header">
        <ng-content></ng-content>
      </div>
      <div class="fc-stepper-content">
        <div 
          *ngFor="let step of steps; let i = index"
          [ngClass]="['fc-step-pane', step.active ? 'fc-step-pane-active' : '']"
          [style.display]="step.active ? 'block' : 'none'"
        >
          <ng-content select="[fc-step-content]"></ng-content>
        </div>
      </div>
      <div class="fc-stepper-footer" *ngIf="showNavigation">
        <button 
          class="fc-btn fc-btn-secondary" 
          (click)="previous()"
          [disabled]="currentStep === 0"
        >
          Trước
        </button>
        <button 
          class="fc-btn fc-btn-primary" 
          (click)="next()"
          [disabled]="currentStep === steps.length - 1"
        >
          Tiếp
        </button>
      </div>
    </div>
  `
})
export class FCStepperComponent implements AfterContentInit {
  @ContentChildren(FCStepComponent) steps!: QueryList<FCStepComponent>;
  @Input() currentStep: number = 0;
  @Input() showNavigation: boolean = true;
  @Output() currentStepChange = new EventEmitter<number>();

  ngAfterContentInit() {
    this.updateSteps();
  }

  updateSteps() {
    this.steps.forEach((step, index) => {
      step.index = index;
      step.active = index === this.currentStep;
      step.completed = index < this.currentStep;
    });
  }

  next() {
    if (this.currentStep < this.steps.length - 1) {
      this.currentStep++;
      this.updateSteps();
      this.currentStepChange.emit(this.currentStep);
    }
  }

  previous() {
    if (this.currentStep > 0) {
      this.currentStep--;
      this.updateSteps();
      this.currentStepChange.emit(this.currentStep);
    }
  }
}
