// src/svelte/FCSwitch.svelte
<script lang="ts">
  import { createEventDispatcher } from 'svelte';
  
  export let checked: boolean = false;
  export let disabled: boolean = false;
  export let label: string = '';
  
  const dispatch = createEventDispatcher();
  
  function onChange(event: Event) {
    const target = event.target as HTMLInputElement;
    checked = target.checked;
    dispatch('checkedChange', checked);
  }
  
  const classes = [
    'fc-switch',
    disabled ? 'fc-switch-disabled' : ''
  ].join(' ');
</script>

<label class={classes}>
  <input 
    type="checkbox" 
    {checked} 
    on:change={onChange}
    {disabled}
  />
  <span class="fc-switch-slider"></span>
  {#if label}
    <span class="fc-switch-label">{label}</span>
  {/if}
</label>

// src/angular/fc-switch.component.ts
import { Component, Input, Output, EventEmitter } from '@angular/core';

@Component({
  selector: 'fc-switch',
  template: `
    <label [ngClass]="['fc-switch', disabled ? 'fc-switch-disabled' : '']">
      <input 
        type="checkbox" 
        [checked]="checked" 
        (change)="onChange($event)"
        [disabled]="disabled"
      >
      <span class="fc-switch-slider"></span>
      <span class="fc-switch-label" *ngIf="label">{{ label }}</span>
    </label>
  `
})
export class FCSwitchComponent {
  @Input() checked: boolean = false;
  @Input() disabled: boolean = false;
  @Input() label: string = '';
  @Output() checkedChange = new EventEmitter<boolean>();

  onChange(event: Event) {
    const target = event.target as HTMLInputElement;
    this.checked = target.checked;
    this.checkedChange.emit(this.checked);
  }
}
