// src/svelte/FCToast.svelte
<script lang="ts">
  export let variant: 'success' | 'danger' | 'warning' | 'info' = 'info';
  export let title: string = '';
  export let autoClose: boolean = true;
  export let delay: number = 5000;

  const classes = [
    'fc-toast',
    `fc-toast-${variant}`
  ].join(' ');
</script>

<div class={classes} role="alert" aria-live="assertive" aria-atomic="true">
  <div class="fc-toast-header">
    <strong class="fc-toast-title">{title}</strong>
    <button type="button" class="fc-toast-close" on:click={() => dispatch('close')} aria-label="Đóng">×</button>
  </div>
  <div class="fc-toast-body">
    <slot />
  </div>
</div>

// src/angular/fc-toast.component.ts
import { Component, Input, Output, EventEmitter } from '@angular/core';

@Component({
  selector: 'fc-toast',
  template: `
    <div [ngClass]="classes" role="alert" aria-live="assertive" aria-atomic="true">
      <div class="fc-toast-header">
        <strong class="fc-toast-title">{{ title }}</strong>
        <button type="button" class="fc-toast-close" (click)="onClose.emit()" aria-label="Đóng">×</button>
      </div>
      <div class="fc-toast-body">
        <ng-content></ng-content>
      </div>
    </div>
  `
})
export class FCToastComponent {
  @Input() variant: 'success' | 'danger' | 'warning' | 'info' = 'info';
  @Input() title: string = '';
  @Input() autoClose: boolean = true;
  @Input() delay: number = 5000;
  @Output() onClose = new EventEmitter<void>();

  get classes() {
    return [
      'fc-toast',
      `fc-toast-${this.variant}`
    ];
  }
}
