// src/react/components/FCAlert.tsx
import React from 'react';

export interface FCAlertProps extends React.HTMLAttributes<HTMLDivElement> {
  variant?: 'primary' | 'secondary' | 'success' | 'danger' | 'warning' | 'info' | 'light' | 'dark';
  className?: string;
  children?: React.ReactNode;
  onClose?: () => void;
  dismissible?: boolean;
}

export const FCAlert: React.FC<FCAlertProps> = ({
  variant = 'primary',
  className = '',
  children,
  onClose,
  dismissible = false,
  ...rest
}) => {
  return (
    <div className={['fc-alert', `fc-alert-${variant}`, dismissible ? 'fc-alert-dismissible' : '', className].filter(Boolean).join(' ')} {...rest}>
      {children}
      {dismissible && (
        <button className="fc-alert-close" onClick={onClose} aria-label="Đóng">×</button>
      )}
    </div>
  );
};

// src/svelte/FCAlert.svelte
<script lang="ts">
  import { createEventDispatcher } from 'svelte';
  
  export let variant: 'primary' | 'secondary' | 'success' | 'danger' | 'warning' | 'info' | 'light' | 'dark' = 'info';
  export let dismissible: boolean = false;
  
  const dispatch = createEventDispatcher();
  
  const classes = [
    'fc-alert',
    `fc-alert-${variant}`,
    dismissible ? 'fc-alert-dismissible' : ''
  ].join(' ');
</script>

<div class={classes} role="alert">
  <div class="fc-alert-content">
    <slot />
  </div>
  {#if dismissible}
    <button 
      type="button" 
      class="fc-alert-close" 
      on:click={() => dispatch('dismiss')}
      aria-label="Đóng"
    >
      ×
    </button>
  {/if}
</div>
