// src/vue/FCAlert.vue
<template>
  <div :class="classes" role="alert">
    <div class="fc-alert-content">
      <slot />
    </div>
    <button
      v-if="dismissible"
      type="button"
      class="fc-alert-close"
      @click="$emit('dismiss')"
      aria-label="Đóng"
    >
      ×
    </button>
  </div>
</template>

<script setup lang="ts">
const props = defineProps({
  variant: { type: String, default: 'info' },
  dismissible: { type: Boolean, default: false }
})
const classes = [
  'fc-alert',
  `fc-alert-${props.variant}`,
  props.dismissible ? 'fc-alert-dismissible' : ''
]
</script>

// src/svelte/FCAlert.svelte
<script lang="ts">
  import { createEventDispatcher } from 'svelte';
  
  export let variant: 'primary' | 'secondary' | 'success' | 'danger' | 'warning' | 'info' | 'light' | 'dark' = 'info';
  export let dismissible: boolean = false;
  
  const dispatch = createEventDispatcher();
  
  const classes = [
    'fc-alert',
    `fc-alert-${variant}`,
    dismissible ? 'fc-alert-dismissible' : ''
  ].join(' ');
</script>

<div class={classes} role="alert">
  <div class="fc-alert-content">
    <slot />
  </div>
  {#if dismissible}
    <button 
      type="button" 
      class="fc-alert-close" 
      on:click={() => dispatch('dismiss')}
      aria-label="Đóng"
    >
      ×
    </button>
  {/if}
</div>
