// src/angular/fc-badge.component.ts
import { Component, Input } from '@angular/core';

@Component({
  selector: 'fc-badge',
  template: `
    <span [ngClass]="classes">
      <ng-content></ng-content>
    </span>
  `
})
export class FCBadgeComponent {
  @Input() variant: 'primary' | 'secondary' | 'success' | 'danger' | 'warning' | 'info' | 'light' | 'dark' = 'primary';
  @Input() size: 'sm' | 'md' | 'lg' = 'md';
  @Input() pill: boolean = false;

  get classes() {
    return [
      'fc-badge',
      `fc-badge-${this.variant}`,
      `fc-badge-${this.size}`,
      this.pill ? 'fc-badge-pill' : ''
    ];
  }
}

// src/svelte/FCBadge.svelte
<script lang="ts">
  export let variant: 'primary' | 'secondary' | 'success' | 'danger' | 'warning' | 'info' | 'light' | 'dark' = 'primary';
  export let size: 'sm' | 'md' | 'lg' = 'md';
  export let pill: boolean = false;
  
  const classes = [
    'fc-badge',
    `fc-badge-${variant}`,
    `fc-badge-${size}`,
    pill ? 'fc-badge-pill' : ''
  ].join(' ');
</script>

<span class={classes}>
  <slot />
</span>
