// src/react/components/FCBadge.tsx
import React from 'react';

export interface FCBadgeProps extends React.HTMLAttributes<HTMLSpanElement> {
  variant?: 'primary' | 'secondary' | 'success' | 'danger' | 'warning' | 'info' | 'light' | 'dark';
  className?: string;
  children?: React.ReactNode;
}

export const FCBadge: React.FC<FCBadgeProps> = ({
  variant = 'primary',
  className = '',
  children,
  ...rest
}) => {
  return (
    <span className={['fc-badge', `fc-badge-${variant}`, className].filter(Boolean).join(' ')} {...rest}>
      {children}
    </span>
  );
};

// src/svelte/FCBadge.svelte
<script lang="ts">
  export let variant: 'primary' | 'secondary' | 'success' | 'danger' | 'warning' | 'info' | 'light' | 'dark' = 'primary';
  export let size: 'sm' | 'md' | 'lg' = 'md';
  export let pill: boolean = false;
  
  const classes = [
    'fc-badge',
    `fc-badge-${variant}`,
    `fc-badge-${size}`,
    pill ? 'fc-badge-pill' : ''
  ].join(' ');
</script>

<span class={classes}>
  <slot />
</span>
