// src/angular/fc-button.component.ts
import { Component, Input, Output, EventEmitter } from '@angular/core';

@Component({
  selector: 'fc-button',
  template: `<button [ngClass]="classes" [type]="type" (click)="onClick.emit($event)"><ng-content></ng-content></button>`
})
export class FCButtonComponent {
  @Input() variant: 'primary' | 'secondary' | 'success' | 'danger' | 'warning' | 'info' | 'light' | 'dark' = 'primary';
  @Input() type: string = 'button';
  @Output() onClick = new EventEmitter<Event>();

  get classes() {
    return [
      'fc-btn',
      `fc-btn-${this.variant}`
    ];
  }
}

// src/svelte/FCButton.svelte
<script lang="ts">
  export let variant: 'primary' | 'secondary' | 'success' | 'danger' | 'warning' | 'info' | 'light' | 'dark' = 'primary';
  export let type: string = 'button';
  import { createEventDispatcher } from 'svelte';
  const dispatch = createEventDispatcher();
</script>

<button class={"fc-btn fc-btn-" + variant} type={type} on:click={(e) => dispatch('click', e)}>
  <slot />
</button>
