// src/angular/fc-card.component.ts
import { Component, Input } from '@angular/core';

@Component({
  selector: 'fc-card',
  template: `
    <div [ngClass]="classes">
      <div class="fc-card-header" *ngIf="header || showHeader">
        <h5 class="fc-card-title">{{ header }}</h5>
        <ng-content select="[fc-card-header]"></ng-content>
      </div>
      <div class="fc-card-body">
        <ng-content></ng-content>
      </div>
      <div class="fc-card-footer" *ngIf="footer || showFooter">
        <ng-content select="[fc-card-footer]"></ng-content>
        <span *ngIf="footer">{{ footer }}</span>
      </div>
    </div>
  `
})
export class FCCardComponent {
  @Input() header: string = '';
  @Input() footer: string = '';
  @Input() variant: 'primary' | 'secondary' | 'success' | 'danger' | 'warning' | 'info' | 'light' | 'dark' = 'light';
  @Input() border: boolean = true;
  @Input() shadow: boolean = false;
  @Input() showHeader: boolean = false;
  @Input() showFooter: boolean = false;

  get classes() {
    return [
      'fc-card',
      `fc-card-${this.variant}`,
      this.border ? 'fc-card-border' : '',
      this.shadow ? 'fc-card-shadow' : ''
    ];
  }
}

// src/svelte/FCCard.svelte
<script lang="ts">
  export let header: string = '';
  export let footer: string = '';
  export let variant: 'primary' | 'secondary' | 'success' | 'danger' | 'warning' | 'info' | 'light' | 'dark' = 'light';
  export let border: boolean = true;
  export let shadow: boolean = false;
  export let showHeader: boolean = false;
  export let showFooter: boolean = false;
  
  const classes = [
    'fc-card',
    `fc-card-${variant}`,
    border ? 'fc-card-border' : '',
    shadow ? 'fc-card-shadow' : ''
  ].join(' ');
</script>

<div class={classes}>
  {#if header || showHeader}
    <div class="fc-card-header">
      <h5 class="fc-card-title">{header}</h5>
      <slot name="header" />
    </div>
  {/if}
  <div class="fc-card-body">
    <slot />
  </div>
  {#if footer || showFooter}
    <div class="fc-card-footer">
      <slot name="footer" />
      {#if footer}
        <span>{footer}</span>
      {/if}
    </div>
  {/if}
</div>
