// src/react/components/FCCard.tsx
import React, { ReactNode, HTMLAttributes } from 'react';

export interface FCCardProps extends Omit<HTMLAttributes<HTMLDivElement>, 'title'> {
  header?: ReactNode;
  footer?: ReactNode;
  title?: string;
  variant?: 'primary' | 'secondary' | 'success' | 'danger' | 'warning' | 'info' | 'light' | 'dark';
  border?: boolean;
  shadow?: boolean;
  showHeader?: boolean;
  showFooter?: boolean;
}

const FCCard: React.FC<FCCardProps> = ({
  header,
  footer,
  title,
  variant = 'light',
  border = true,
  shadow = false,
  showHeader = false,
  showFooter = false,
  className = '',
  children,
  ...rest
}) => {
  const classes = [
    'fc-card',
    `fc-card-${variant}`,
    border ? 'fc-card-border' : '',
    shadow ? 'fc-card-shadow' : '',
    className
  ].join(' ');
  return (
    <div className={classes} {...rest}>
      {(header || showHeader) && (
        <div className="fc-card-header">
          {title && <h5 className="fc-card-title">{title}</h5>}
          {header}
        </div>
      )}
      <div className="fc-card-body">{children}</div>
      {(footer || showFooter) && (
        <div className="fc-card-footer">
          {footer}
        </div>
      )}
    </div>
  );
};

export default FCCard;

// src/svelte/FCCard.svelte
<script lang="ts">
  export let header: string = '';
  export let footer: string = '';
  export let variant: 'primary' | 'secondary' | 'success' | 'danger' | 'warning' | 'info' | 'light' | 'dark' = 'light';
  export let border: boolean = true;
  export let shadow: boolean = false;
  export let showHeader: boolean = false;
  export let showFooter: boolean = false;
  
  const classes = [
    'fc-card',
    `fc-card-${variant}`,
    border ? 'fc-card-border' : '',
    shadow ? 'fc-card-shadow' : ''
  ].join(' ');
</script>

<div class={classes}>
  {#if header || showHeader}
    <div class="fc-card-header">
      <h5 class="fc-card-title">{header}</h5>
      <slot name="header" />
    </div>
  {/if}
  <div class="fc-card-body">
    <slot />
  </div>
  {#if footer || showFooter}
    <div class="fc-card-footer">
      <slot name="footer" />
      {#if footer}
        <span>{footer}</span>
      {/if}
    </div>
  {/if}
</div>
