// src/angular/fc-skeleton.component.ts
import { Component, Input } from '@angular/core';

@Component({
  selector: 'fc-skeleton',
  template: `
    <div 
      [ngClass]="classes"
      [style.width]="width"
      [style.height]="height"
    ></div>
  `
})
export class FCSkeletonComponent {
  @Input() variant: 'text' | 'circular' | 'rectangular' = 'text';
  @Input() width: string = '100%';
  @Input() height: string = '1rem';
  @Input() animated: boolean = true;

  get classes() {
    return [
      'fc-skeleton',
      `fc-skeleton-${this.variant}`,
      this.animated ? 'fc-skeleton-animated' : ''
    ];
  }
}

// src/svelte/FCSkeleton.svelte
<script lang="ts">
  export let variant: 'text' | 'circular' | 'rectangular' = 'text';
  export let width: string = '100%';
  export let height: string = '1rem';
  export let animated: boolean = true;
  
  const classes = [
    'fc-skeleton',
    `fc-skeleton-${variant}`,
    animated ? 'fc-skeleton-animated' : ''
  ].join(' ');
</script>

<div class={classes} style="width: {width}; height: {height}"></div>
