// src/vue/FCStepper.vue
<template>
  <div class="fc-stepper">
    <div class="fc-stepper-header">
      <slot name="header" />
    </div>
    <div class="fc-stepper-content">
      <slot />
    </div>
    <div class="fc-stepper-footer" v-if="showNavigation">
      <button class="fc-btn fc-btn-secondary" @click="previous" :disabled="currentStep === 0">Trước</button>
      <button class="fc-btn fc-btn-primary" @click="next" :disabled="currentStep === steps - 1">Tiếp</button>
    </div>
  </div>
</template>

<script setup lang="ts">
import { ref, watch } from 'vue'
const props = defineProps({
  currentStep: { type: Number, default: 0 },
  steps: { type: Number, default: 1 },
  showNavigation: { type: Boolean, default: true }
})
const emit = defineEmits(['update:currentStep'])
const current = ref(props.currentStep)
watch(() => props.currentStep, v => current.value = v)
function next() {
  if (current.value < props.steps - 1) emit('update:currentStep', current.value + 1)
}
function previous() {
  if (current.value > 0) emit('update:currentStep', current.value - 1)
}
</script>

// src/svelte/FCStepper.svelte
<script lang="ts">
  import { createEventDispatcher } from 'svelte';
  
  export let currentStep: number = 0;
  export let steps: Array<{title: string, description?: string}> = [];
  export let showNavigation: boolean = true;
  
  const dispatch = createEventDispatcher();
  
  function next() {
    if (currentStep < steps.length - 1) {
      currentStep++;
      dispatch('currentStepChange', currentStep);
    }
  }
  
  function previous() {
    if (currentStep > 0) {
      currentStep--;
      dispatch('currentStepChange', currentStep);
    }
  }
</script>

<div class="fc-stepper">
  <div class="fc-stepper-header">
    {#each steps as step, i}
      <div class="fc-step {currentStep === i ? 'fc-step-active' : ''} {i < currentStep ? 'fc-step-completed' : ''}">
        <div class="fc-step-icon">
          {#if i < currentStep}
            <span>✓</span>
          {:else}
            <span>{i + 1}</span>
          {/if}
        </div>
        <div class="fc-step-content">
          <div class="fc-step-title">{step.title}</div>
          {#if step.description}
            <div class="fc-step-description">{step.description}</div>
          {/if}
        </div>
      </div>
    {/each}
  </div>
  <div class="fc-stepper-content">
    <slot />
  </div>
  {#if showNavigation}
    <div class="fc-stepper-footer">
      <button class="fc-btn fc-btn-secondary" on:click={previous} disabled={currentStep === 0}>
        Trước
      </button>
      <button class="fc-btn fc-btn-primary" on:click={next} disabled={currentStep === steps.length - 1}>
        Tiếp
      </button>
    </div>
  {/if}
</div>
