// src/react/components/FCSwitch.tsx
import React, { InputHTMLAttributes } from 'react';

export interface FCSwitchProps extends Omit<InputHTMLAttributes<HTMLInputElement>, 'onChange'> {
  checked?: boolean;
  disabled?: boolean;
  label?: string;
  onChange?: (checked: boolean) => void;
}

const FCSwitch: React.FC<FCSwitchProps> = ({
  checked = false,
  disabled = false,
  label = '',
  onChange,
  className = '',
  ...rest
}) => {
  const classes = [
    'fc-switch',
    disabled ? 'fc-switch-disabled' : '',
    className
  ].join(' ');
  return (
    <label className={classes}>
      <input
        type="checkbox"
        checked={checked}
        disabled={disabled}
        onChange={e => onChange && onChange(e.target.checked)}
        {...rest}
      />
      <span className="fc-switch-slider"></span>
      {label && <span className="fc-switch-label">{label}</span>}
    </label>
  );
};

export default FCSwitch;

// src/svelte/FCSwitch.svelte
<script lang="ts">
  import { createEventDispatcher } from 'svelte';
  
  export let checked: boolean = false;
  export let disabled: boolean = false;
  export let label: string = '';
  
  const dispatch = createEventDispatcher();
  
  function onChange(event: Event) {
    const target = event.target as HTMLInputElement;
    checked = target.checked;
    dispatch('checkedChange', checked);
  }
  
  const classes = [
    'fc-switch',
    disabled ? 'fc-switch-disabled' : ''
  ].join(' ');
</script>

<label class={classes}>
  <input 
    type="checkbox" 
    {checked} 
    on:change={onChange}
    {disabled}
  />
  <span class="fc-switch-slider"></span>
  {#if label}
    <span class="fc-switch-label">{label}</span>
  {/if}
</label>
