// src/vue/FCSwitch.vue
<template>
  <label :class="['fc-switch', disabled ? 'fc-switch-disabled' : '']">
    <input
      type="checkbox"
      :checked="modelValue"
      @change="onChange"
      :disabled="disabled"
    />
    <span class="fc-switch-slider"></span>
    <span class="fc-switch-label" v-if="label">{{ label }}</span>
  </label>
</template>

<script setup lang="ts">
const props = defineProps({
  modelValue: { type: Boolean, default: false },
  disabled: { type: Boolean, default: false },
  label: { type: String, default: '' }
})
const emit = defineEmits(['update:modelValue'])
function onChange(e: Event) {
  emit('update:modelValue', (e.target as HTMLInputElement).checked)
}
</script>

// src/svelte/FCSwitch.svelte
<script lang="ts">
  import { createEventDispatcher } from 'svelte';
  
  export let checked: boolean = false;
  export let disabled: boolean = false;
  export let label: string = '';
  
  const dispatch = createEventDispatcher();
  
  function onChange(event: Event) {
    const target = event.target as HTMLInputElement;
    checked = target.checked;
    dispatch('checkedChange', checked);
  }
  
  const classes = [
    'fc-switch',
    disabled ? 'fc-switch-disabled' : ''
  ].join(' ');
</script>

<label class={classes}>
  <input 
    type="checkbox" 
    {checked} 
    on:change={onChange}
    {disabled}
  />
  <span class="fc-switch-slider"></span>
  {#if label}
    <span class="fc-switch-label">{label}</span>
  {/if}
</label>
