// src/vue/FCTooltip.vue
<template>
  <div
    :class="['fc-tooltip', show ? 'fc-tooltip-show' : '']"
    role="tooltip"
    v-show="show"
  >
    {{ content }}
  </div>
</template>

<script setup lang="ts">
const props = defineProps({
  content: { type: String, default: '' },
  placement: { type: String, default: 'top' },
  show: { type: Boolean, default: false }
})
const emit = defineEmits(['update:show'])
</script>

// src/svelte/FCTooltip.svelte
<script lang="ts">
  import { createEventDispatcher } from 'svelte';
  
  export let content: string = '';
  export let placement: 'top' | 'bottom' | 'left' | 'right' = 'top';
  export let show: boolean = false;
  
  const dispatch = createEventDispatcher();
  
  const classes = [
    'fc-tooltip',
    show ? 'fc-tooltip-show' : ''
  ].join(' ');
</script>

<div class={classes} role="tooltip" style="display: {show ? 'block' : 'none'}">
  {content}
</div>
