// src/react/components/FCToast.tsx
import React, { useEffect } from 'react';

export interface FCToastProps extends React.HTMLAttributes<HTMLDivElement> {
  type?: 'info' | 'success' | 'warning' | 'danger';
  message: string;
  duration?: number;
  onClose?: () => void;
  className?: string;
}

export const FCToast: React.FC<FCToastProps> = ({
  type = 'info',
  message,
  duration = 3000,
  onClose,
  className = '',
  ...rest
}) => {
  useEffect(() => {
    if (duration > 0) {
      const timer = setTimeout(() => {
        onClose?.();
      }, duration);
      return () => clearTimeout(timer);
    }
  }, [duration, onClose]);

  return (
    <div className={['fc-toast', `fc-toast-${type}`, className].filter(Boolean).join(' ')} {...rest}>
      {message}
      <button className="fc-toast-close" onClick={onClose} aria-label="Đóng">×</button>
    </div>
  );
};

// src/svelte/FCToast.svelte
<script lang="ts">
  export let variant: 'success' | 'danger' | 'warning' | 'info' = 'info';
  export let title: string = '';
  export let autoClose: boolean = true;
  export let delay: number = 5000;

  const classes = [
    'fc-toast',
    `fc-toast-${variant}`
  ].join(' ');
</script>

<div class={classes} role="alert" aria-live="assertive" aria-atomic="true">
  <div class="fc-toast-header">
    <strong class="fc-toast-title">{title}</strong>
    <button type="button" class="fc-toast-close" on:click={() => dispatch('close')} aria-label="Đóng">×</button>
  </div>
  <div class="fc-toast-body">
    <slot />
  </div>
</div>
