// src/svelte/FCButton.svelte
<script lang="ts">
  export let variant: 'primary' | 'secondary' | 'success' | 'danger' | 'warning' | 'info' | 'light' | 'dark' = 'primary';
  export let type: string = 'button';
  import { createEventDispatcher } from 'svelte';
  const dispatch = createEventDispatcher();
</script>

<button class={"fc-btn fc-btn-" + variant} type={type} on:click={(e) => dispatch('click', e)}>
  <slot />
</button>

// src/react/components/FCButton.tsx
import React from 'react';

export interface FCButtonProps extends React.ButtonHTMLAttributes<HTMLButtonElement> {
  variant?: 'primary' | 'secondary' | 'success' | 'danger' | 'warning' | 'info' | 'light' | 'dark';
  size?: 'sm' | 'md' | 'lg';
}

export const FCButton: React.FC<FCButtonProps> = ({
  variant = 'primary',
  size = 'md',
  className = '',
  children,
  ...rest
}) => {
  const classes = [
    'fc-btn',
    `fc-btn-${variant}`,
    size !== 'md' ? `fc-btn-${size}` : '',
    className
  ].filter(Boolean).join(' ');

  return (
    <button className={classes} {...rest}>
      {children}
    </button>
  );
};
