// src/svelte/FCTooltip.svelte
<script lang="ts">
  import { createEventDispatcher } from 'svelte';
  
  export let content: string = '';
  export let placement: 'top' | 'bottom' | 'left' | 'right' = 'top';
  export let show: boolean = false;
  
  const dispatch = createEventDispatcher();
  
  const classes = [
    'fc-tooltip',
    show ? 'fc-tooltip-show' : ''
  ].join(' ');
</script>

<div class={classes} role="tooltip" style="display: {show ? 'block' : 'none'}">
  {content}
</div>

// src/react/components/FCTooltip.tsx
import React, { ReactNode, HTMLAttributes } from 'react';

export interface FCTooltipProps extends Omit<HTMLAttributes<HTMLDivElement>, 'content'> {
  content?: string;
  placement?: 'top' | 'bottom' | 'left' | 'right';
  show?: boolean;
  children?: ReactNode;
}

const FCTooltip: React.FC<FCTooltipProps> = ({
  content = '',
  placement = 'top',
  show = false,
  children,
  className = '',
  ...rest
}) => {
  const classes = [
    'fc-tooltip',
    show ? 'fc-tooltip-show' : '',
    className
  ].join(' ');
  return (
    <div className={classes} role="tooltip" {...rest} style={{ display: show ? 'block' : 'none' }}>
      {content}
      {children}
    </div>
  );
};

export default FCTooltip;
