// src/svelte/FCBadge.svelte
<script lang="ts">
  export let variant: 'primary' | 'secondary' | 'success' | 'danger' | 'warning' | 'info' | 'light' | 'dark' = 'primary';
  export let size: 'sm' | 'md' | 'lg' = 'md';
  export let pill: boolean = false;
  
  const classes = [
    'fc-badge',
    `fc-badge-${variant}`,
    `fc-badge-${size}`,
    pill ? 'fc-badge-pill' : ''
  ].join(' ');
</script>

<span class={classes}>
  <slot />
</span>

// src/vue/FCBadge.vue
<template>
  <span :class="classes">
    <slot />
  </span>
</template>

<script setup lang="ts">
const props = defineProps({
  variant: { type: String, default: 'primary' },
  size: { type: String, default: 'md' },
  pill: { type: Boolean, default: false }
})
const classes = [
  'fc-badge',
  `fc-badge-${props.variant}`,
  `fc-badge-${props.size}`,
  props.pill ? 'fc-badge-pill' : ''
]
</script>
