// src/svelte/FCCard.svelte
<script lang="ts">
  export let header: string = '';
  export let footer: string = '';
  export let variant: 'primary' | 'secondary' | 'success' | 'danger' | 'warning' | 'info' | 'light' | 'dark' = 'light';
  export let border: boolean = true;
  export let shadow: boolean = false;
  export let showHeader: boolean = false;
  export let showFooter: boolean = false;
  
  const classes = [
    'fc-card',
    `fc-card-${variant}`,
    border ? 'fc-card-border' : '',
    shadow ? 'fc-card-shadow' : ''
  ].join(' ');
</script>

<div class={classes}>
  {#if header || showHeader}
    <div class="fc-card-header">
      <h5 class="fc-card-title">{header}</h5>
      <slot name="header" />
    </div>
  {/if}
  <div class="fc-card-body">
    <slot />
  </div>
  {#if footer || showFooter}
    <div class="fc-card-footer">
      <slot name="footer" />
      {#if footer}
        <span>{footer}</span>
      {/if}
    </div>
  {/if}
</div>

// src/vue/FCCard.vue
<template>
  <div :class="classes">
    <div class="fc-card-header" v-if="header || showHeader">
      <h5 class="fc-card-title">{{ header }}</h5>
      <slot name="header" />
    </div>
    <div class="fc-card-body">
      <slot />
    </div>
    <div class="fc-card-footer" v-if="footer || showFooter">
      <slot name="footer" />
      <span v-if="footer">{{ footer }}</span>
    </div>
  </div>
</template>

<script setup lang="ts">
const props = defineProps({
  header: { type: String, default: '' },
  footer: { type: String, default: '' },
  variant: { type: String, default: 'light' },
  border: { type: Boolean, default: true },
  shadow: { type: Boolean, default: false },
  showHeader: { type: Boolean, default: false },
  showFooter: { type: Boolean, default: false }
})
const classes = [
  'fc-card',
  `fc-card-${props.variant}`,
  props.border ? 'fc-card-border' : '',
  props.shadow ? 'fc-card-shadow' : ''
]
</script>
