// src/svelte/FCInput.svelte
<script lang="ts">
  import { createEventDispatcher } from 'svelte';
  
  export let value: string = '';
  export let type: 'text' | 'email' | 'password' | 'number' | 'tel' | 'url' = 'text';
  export let placeholder: string = '';
  export let disabled: boolean = false;
  export let readonly: boolean = false;
  export let size: 'sm' | 'md' | 'lg' = 'md';
  
  const dispatch = createEventDispatcher();
  
  const classes = [
    'fc-input',
    `fc-input-${size}`
  ].join(' ');
  
  function onInput(event: Event) {
    const target = event.target as HTMLInputElement;
    value = target.value;
    dispatch('valueChange', value);
  }
</script>

<input 
  class={classes}
  {type}
  {placeholder}
  {value}
  {disabled}
  {readonly}
  on:input={onInput}
/>

// src/vue/FCInput.vue
<template>
  <input
    :class="classes"
    :type="type"
    :placeholder="placeholder"
    :value="modelValue"
    :disabled="disabled"
    :readonly="readonly"
    @input="$emit('update:modelValue', $event.target.value)"
  />
</template>

<script setup lang="ts">
const props = defineProps({
  modelValue: { type: String, default: '' },
  type: { type: String, default: 'text' },
  placeholder: { type: String, default: '' },
  disabled: { type: Boolean, default: false },
  readonly: { type: Boolean, default: false },
  size: { type: String, default: 'md' }
})
const classes = [
  'fc-input',
  `fc-input-${props.size}`
]
</script>
