// src/svelte/FCSelect.svelte
<script lang="ts">
  import { createEventDispatcher } from 'svelte';
  
  export let value: string | number = '';
  export let options: Array<{value: string | number, label: string, disabled?: boolean}> = [];
  export let placeholder: string = '';
  export let disabled: boolean = false;
  export let size: 'sm' | 'md' | 'lg' = 'md';
  
  const dispatch = createEventDispatcher();
  
  const classes = [
    'fc-select',
    `fc-select-${size}`
  ].join(' ');
  
  function onChange(event: Event) {
    const target = event.target as HTMLSelectElement;
    value = target.value;
    dispatch('valueChange', value);
  }
</script>

<select 
  class={classes}
  {value}
  {disabled}
  on:change={onChange}
>
  {#if placeholder}
    <option value="">{placeholder}</option>
  {/if}
  {#each options as option}
    <option value={option.value} disabled={option.disabled}>
      {option.label}
    </option>
  {/each}
</select>

// src/vue/FCSelect.vue
<template>
  <select
    :class="classes"
    :value="modelValue"
    :disabled="disabled"
    @change="$emit('update:modelValue', $event.target.value)"
  >
    <option value="" v-if="placeholder">{{ placeholder }}</option>
    <option
      v-for="option in options"
      :key="option.value"
      :value="option.value"
      :disabled="option.disabled"
    >
      {{ option.label }}
    </option>
  </select>
</template>

<script setup lang="ts">
const props = defineProps({
  modelValue: { type: [String, Number], default: '' },
  options: { type: Array, default: () => [] },
  placeholder: { type: String, default: '' },
  disabled: { type: Boolean, default: false },
  size: { type: String, default: 'md' }
})
const classes = [
  'fc-select',
  `fc-select-${props.size}`
]
</script>
