// src/svelte/FCSkeleton.svelte
<script lang="ts">
  export let variant: 'text' | 'circular' | 'rectangular' = 'text';
  export let width: string = '100%';
  export let height: string = '1rem';
  export let animated: boolean = true;
  
  const classes = [
    'fc-skeleton',
    `fc-skeleton-${variant}`,
    animated ? 'fc-skeleton-animated' : ''
  ].join(' ');
</script>

<div class={classes} style="width: {width}; height: {height}"></div>

// src/vue/FCSkeleton.vue
<template>
  <div :class="classes" :style="{ width, height }"></div>
</template>

<script setup lang="ts">
const props = defineProps({
  variant: { type: String, default: 'text' },
  width: { type: String, default: '100%' },
  height: { type: String, default: '1rem' },
  animated: { type: Boolean, default: true }
})
const classes = [
  'fc-skeleton',
  `fc-skeleton-${props.variant}`,
  props.animated ? 'fc-skeleton-animated' : ''
]
</script>
