// src/svelte/FCTextarea.svelte
<script lang="ts">
  import { createEventDispatcher } from 'svelte';
  
  export let value: string = '';
  export let placeholder: string = '';
  export let disabled: boolean = false;
  export let readonly: boolean = false;
  export let rows: number = 3;
  export let cols: number = 50;
  export let size: 'sm' | 'md' | 'lg' = 'md';
  
  const dispatch = createEventDispatcher();
  
  const classes = [
    'fc-textarea',
    `fc-textarea-${size}`
  ].join(' ');
  
  function onInput(event: Event) {
    const target = event.target as HTMLTextAreaElement;
    value = target.value;
    dispatch('valueChange', value);
  }
</script>

<textarea 
  class={classes}
  {placeholder}
  {value}
  {disabled}
  {readonly}
  {rows}
  {cols}
  on:input={onInput}
/>

// src/vue/FCTextarea.vue
<template>
  <textarea
    :class="classes"
    :placeholder="placeholder"
    :value="modelValue"
    :disabled="disabled"
    :readonly="readonly"
    :rows="rows"
    :cols="cols"
    @input="$emit('update:modelValue', $event.target.value)"
  />
</template>

<script setup lang="ts">
const props = defineProps({
  modelValue: { type: String, default: '' },
  placeholder: { type: String, default: '' },
  disabled: { type: Boolean, default: false },
  readonly: { type: Boolean, default: false },
  rows: { type: Number, default: 3 },
  cols: { type: Number, default: 50 },
  size: { type: String, default: 'md' }
})
const classes = [
  'fc-textarea',
  `fc-textarea-${props.size}`
]
</script>
